// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzeDA3eI4GlAEkf7rxQK8WmSUnhWnf320',
    appId: '1:890963695000:web:b6ccc544a56fa3255cc7ed',
    messagingSenderId: '890963695000',
    projectId: 'noti-app-e9e54',
    authDomain: 'noti-app-e9e54.firebaseapp.com',
    storageBucket: 'noti-app-e9e54.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTEVTHa9WJyDFG6C8zxhDiK2yfJRltZaM',
    appId: '1:890963695000:android:e7f97646d5ea2a355cc7ed',
    messagingSenderId: '890963695000',
    projectId: 'noti-app-e9e54',
    storageBucket: 'noti-app-e9e54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR3otfUCv7z1Fr7A8DzM1xgn7xfp6cbok',
    appId: '1:890963695000:ios:c0ef0c9ba57a47c25cc7ed',
    messagingSenderId: '890963695000',
    projectId: 'noti-app-e9e54',
    storageBucket: 'noti-app-e9e54.appspot.com',
    iosClientId: '890963695000-o0bcc4pp6ml52a0ire9rpd7b85jhf0mj.apps.googleusercontent.com',
    iosBundleId: 'com.example.fSesion11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR3otfUCv7z1Fr7A8DzM1xgn7xfp6cbok',
    appId: '1:890963695000:ios:c0ef0c9ba57a47c25cc7ed',
    messagingSenderId: '890963695000',
    projectId: 'noti-app-e9e54',
    storageBucket: 'noti-app-e9e54.appspot.com',
    iosClientId: '890963695000-o0bcc4pp6ml52a0ire9rpd7b85jhf0mj.apps.googleusercontent.com',
    iosBundleId: 'com.example.fSesion11',
  );
}
